{% set version = '0.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyjqui
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyjqui_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyjqui/shinyjqui_{{ version }}.tar.gz
  sha256: 3d218466c161a3b155ce061b5b5912a12cd4de077df3ae336fa6a33b6b979158

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-shiny >=0.14.0
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-shiny >=0.14.0

test:
  commands:
    - $R -e "library('shinyjqui')"           # [not win]
    - "\"%R%\" -e \"library('shinyjqui')\""  # [win]

about:
  home: https://github.com/yang-tang/shinyjqui
  license: MIT
  summary: An extension to shiny that brings interactions and animation effects from 'jQuery
    UI' library.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinyjqui
# Type: Package
# Title: 'jQuery UI' Interactions and Effects for Shiny
# Version: 0.3.3
# Authors@R: person("Yang", "Tang", email = "tang_yang@outlook.com", role = c("aut", "cre"))
# Maintainer: Yang Tang <tang_yang@outlook.com>
# Description: An extension to shiny that brings interactions and animation effects from 'jQuery UI' library.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.2.0)
# Imports: shiny (>= 0.14.0), htmltools, htmlwidgets, jsonlite
# Suggests: ggplot2, highcharter, knitr, rmarkdown
# URL: https://github.com/yang-tang/shinyjqui
# BugReports: https://github.com/yang-tang/shinyjqui/issues
# RoxygenNote: 7.0.2
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-02-03 13:57:45 UTC; tangy53
# Author: Yang Tang [aut, cre]
# Repository: CRAN
# Date/Publication: 2020-02-03 15:50:05 UTC
