travis:
  secure:
    BINSTAR_TOKEN: NX4G4PnZDwxaADenGlQbS2AydGcdY+Zn5VMe47N8S73O87QpvRVpGtJVc2XUwfSeArI7pkycpokWNthrpP7c3KU9yHO5I1f/FNUYRYJgpj7nMF/3GyKWaBCyW4y82/tQc2lE1WkCYkn375kVMu/LI0K0QZiQ1/KiWZqKLBdAJHReiQd+nhH/zyiYH4ml12S22zOaCtzV0ZlWiracKSDrmqxD5XJ0RdrvzG8sHeMl9h7DEEvIWYI6xImpOVAPsMqlI45NEIORqmqAiv4B1NE4IcDK/W552OlUzT3UFgIBDIJQzLtAl0WC3F7qAsJnO633qNdrkFqNblcXq/5g3v19NF2A3svF4gdoMfb02/tSuh1INC6saDkcdz757L5JWDAiuYjJMr9Ub3dKRIG9T+aOt7RCkf+eWOBCtHzf+IW5dT4xnel8CtOKT7wEx8BidreemIhhPodjgt2TInTyH76nu2bzOL67awsSSRcvmA5MpPYUvnvOC8Ijf8/wtSNp3MX3+6/C9GoVNXZr9AbUozG4dCwcMwFKcdfApL6yoONDs2zezwbuDZFxFjR95obsncJZp6/gR0KDmnNanA61D67xsLVExyQgRiFnOQpgouEl1bseCN87bCu0cJMFIkZ8t4iJIaFdfV5DmKmRpfz3KYRtvO156YfkPYwJrrv+rMZEGjg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
